{{- if .Values.imageCredentials.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-image-pull-secrets
  namespace: kubeflow
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-image-pull-secrets
  namespace: istio-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
