namespace: kubeflow
kfpMinioImage: build-harbor.alauda.cn/3rdparty/kubeflow/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance

exports:
  secrets:
    minioAK: minio
    minioSK: minio123
    
