apiVersion: v2
name: minio
version: "1.0"
kubeVersion: ">=1.17.0"
description: "MinIO"
type: application
keywords:
  - "Minio"
  - "storage"
  - "S3"
sources:
  - https://github.com/alauda/kubeflow-chart
maintainers:
  - name: typhoonzero
    email: typhoonzero1986@gmail.com
appVersion: "1.0"