name: ChartsE2E

on:
  push:
    branches:
      - pull_request

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Run E2E Tests
        run: |
          helm install istio charts/istio
          kubectl -n istio-system get po
